#!/bin/sh
### BEGIN INIT INFO
# Provides:          Sensorplatform application
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the sensorplatform application.
# Description:       
### END INIT INFO
 
# Actions
case "$1" in
	start)
		/sbin/hwclock -s
		#/opt/vc/bin/tvservice -o 
		cd /home/administrator/Sensorplatform
        /lib/jvm/jdk1.8.0_101/bin/java -cp "bin/*" de.fhg.fit.biomos.sensorplatform.main.Main >> sensorplatform.txt 2>&1 &
        ;;
    stop)
        killall java
		killall wvdial
		killall pppd
        ;;
    restart)
        killall java
		killall wvdial
		killall pppd
		/sbin/hwclock -s
		#/opt/vc/bin/tvservice -o
		cd /home/administrator/Sensorplatform
        /lib/jvm/jdk1.8.0_101/bin/java -cp "bin/*" de.fhg.fit.biomos.sensorplatform.main.Main >> sensorplatform.txt 2>&1 &
        ;;
esac
 
exit 0